### ISSUE TITLE
Monad transformers

### ISSUE THREAD

**Issue by RPallas92** [spebbe/dartz#3]
First of all, thanks for such extensive library.
Usually it’s helpful to use a Reader<Future<Either>> monad stack to:
- inject dependencies
- perform asynchronous operations
- and return either a result or an error

Is it possible to achieve this in dartz?

**Comment by josete89** [comment]
+1

**Comment by spebbe** [comment]
Hi!

There is no Reader or ReaderT/Kleisli in dartz yet... However, there is `Evaluation<E,R,W,S,A>`, which corresponds roughly to the mega stack `Future<Either<E, Reader<R, A> + Writer<W, A> + State<S, A>>>`, which is what I often find myself with after stacking transformers in scala. Since this is a hard coded stack, you cannot alter the layering of monadic effects without copy-pasting, but maybe it handles the use cases you have?

Here's an example of basic usage, with the Writer and State parts of the stack left unused (=Unit):
```dart
import 'dart:async';
import 'package:dartz/dartz.dart';

main() async {
  final M = new EvaluationMonad<String, int, Unit, Unit>(UnitMi);

  Future<int> doAmazingStuffWithAnInt(int i) =>
    new Future.delayed(new Duration(seconds: 1), () => i*2);

  final validateConf = M.ask()
    .bind((i) => i != 0 ? M.pure(i) : M.raiseError("a zero... rude!"));

  final program = validateConf
    .andThen(M.ask())
    .bind((i) => M.liftFuture(doAmazingStuffWithAnInt(i))
    .map((result) => "The conf $i yielded the amazing result $result!"));

  print(await program.value(0, unit));
  print(await program.value(15, unit));
}
```

I have nearly given up on trying to do freely stackable monad transformers in Dart, since the lack of higher-kinded types makes it (close to?) impossible to retain a properly typed API, but I'll definitely add some form of standalone Reader implementation eventually.

Hope that helps -- feedback and suggestions are very welcome!

/Björn

**Comment by mateusfccp** [comment]
@spebbe Why is there no Reader monad in `dartz`? Is it not possible? I tried to implement it by myself and got caught with contravariance problems.

For example, this code
```dart
class Reader<A, B> implements Functor<B Function(A)> {}
```

would result on the following error:

```
'A' can't be used contravariantly or invariantly in 'Functor<B Function(A)>'.
Try not using class type parameters in types of formal parameters of function types, nor in explicitly contravariant or invariant superinterfaces.dart(wrong_type_parameter_variance_in_superinterface)
```

**Comment by spebbe** [comment]
Hi @mateusfccp!

You could do something like this:
```dart
class Reader<R, A> implements MonadOps<Reader<R, dynamic>, A> {
  final Function1<R, A> run;
  Reader(this.run);
  .
  .
  .
}
```

I don't think it's possible to write a type safe monad instance for un-wrapped reader functions directly in Dart (but not 100% sure). That's probably the main reason why I haven't included it yet. The need for wrapper objects/stack safety/etc usually leads me to using `Evaluation` in the end instead.

It should really be in the library though, for completeness at the least. If you feel like taking a stab at it, I'd be happy to include it! Otherwise, I can give it a spin.

**Comment by mateusfccp** [comment]
@spebbe I think https://github.com/dart-lang/language/issues/213 would help in our case for a type-safe implementation, although there's no promise nor date for it to be implemented.

**Comment by mateusfccp** [comment]
@spebbe According to @eernstg, on dart-lang/language#213, we can use something like:

```dart
class Functor<out A> {}
class Reader<in A, out B> implements Functor<B Function(A)> {}
```

However, this is only available since Dart 2.9, and `dartz` is currently compatible with Dart 1.

**Comment by spebbe** [comment]
Thanks for this -- this is great news! I'd heard rumors that declaration-site variance control was being worked on, but didn't know that it had been released. I'm baffled that I can't find **_any_** mention of this important language change anywhere in the SDK changelog, dart.dev or any of the usual channels.

And yes, this should make it possible to declare standalone type class instances for "naked" reader functions (e.g. `Monad`, not `MonadOps`). It should also be possible to add infix `map`/`flatMap`/etc using extensions if desired.

**Comment by eernstg** [comment]
> is is only available since Dart 2.9

Declaration-site variance has not yet been released, so it's not enough to switch to Dart 2.9.

**Comment by spebbe** [comment]
Aww... well the lack of an announcement makes more sense now :-)
Thanks for clarifying @eernstg! I hope you are able to release it eventually – fingers crossed!

**Comment by mateusfccp** [comment]
I see... I though it was available through `enable-experiments` because it's declared on https://github.com/dart-lang/sdk/blob/master/tools/experimental_features.yaml. Plus, if I try to use it on any file it hints me that I need to have Dart 2.9 or greater to use it.

Sorry for the misinformation.

**Comment by eernstg** [comment]
A feature may be available through `enable-experiments`, but that doesn't mean that it is guaranteed to work, or that a released version of the feature will work in the same way. The hint is obsolete, I've reported that (https://github.com/dart-lang/sdk/issues/43379).

**Comment by mateusfccp** [comment]
Thanks, @eernstg.
