### ISSUE TITLE
Error because subtype 'dynamic' does not match if using equals() in expexted() 

### ISSUE THREAD

**Issue by blaueeiner** [spebbe/dartz#38]
Hi Dartz Community!
I got a problem related to equality match with subtypes.
I use dartz in this context of the problem connected with flutter_test.

This is my code snippet that is relevant:
expect(result, equals(Right([tActivity])));
and I get the following error when running tests:

"Expected: Right<dynamic, List>:<Right([ActivityModel])>
Actual: Right<Failure, List>:<Right([ActivityModel])>"

The problem is caused by the little type difference 'dynamic' <-> 'Failure'.

This behaviour might be correct but is there another way for expecting the code to pass?

**Comment by spebbe** [comment]
hi @blaueeiner!

try adding explicit type annotations, like `expect(result, equals(Right<Failure, List>([tActivity])));`.

**Comment by mateusfccp** [comment]
This happens because both `expect` and  `equals` receive `dynamic` as parameter.

This issue is similar to #33. However, unlike #33, you can't pass type arguments to the function.

I don't know if this will work, but did you try to make an explicit cast? Like `expect(result, equals(Right<dynamic, List>([tActivity])))`.

**Comment by blaueeiner** [comment]
It fixed it! Thank you guys :)
