### ISSUE TITLE
Support for Result<T,E> for returning Ok, Err

### ISSUE THREAD

**Issue by iangregsondev** [spebbe/dartz#58]
Hi,

I wondered if anybody has considered having a Result - similar to Either but already has Ok, Err constructs.

More info here https://github.com/hqoss/monads/tree/master/lib/result. (typescript implementation)

and original rust implementation https://doc.rust-lang.org/std/result/enum.Result.html

Cheers

**Comment by iangregsondev** [comment]
I did find this, but it would be nice to have it integrated directly into dartz backed by Option and other constructs

https://pub.dev/packages/simple_result

**Comment by mateusfccp** [comment]
I don't see a general way of making this work. The way, for example, Rust works, is by typealiasing `Either<Err, T>` to `Result<T>`. Indeed, it's very common for the programmer to alias it's own error types to make a custom `Result`.

The Dart team is somewhat working on non-function typedefs (as the current typedef only works for functions), and as soon this feature is provided, you will be able to make you results by using `typedef Result<T> = Either<YourErrorType, T>`

**Comment by iangregsondev** [comment]
I was thinking more of a way to introduce Result<T,E> as a new construct built on top of Option, much like Either.

Of course, I could you implement my own Result<T,E> but I just thought it would be something of benefit to the library.

I

**Comment by mateusfccp** [comment]
> I was thinking more of a way to introduce Result<T,E> as a new construct built on top of Option, much like Either.
> 
> Of course, I could you implement my own Result<T,E> but I just thought it would be something of benefit to the library.

This only makes sense as long as there's a default `Err`, but it would really not be useful. What are you thinking, in using `Exception` as the default left value? Because usually, when people use `Either` (or `Result`) for error handling, they also implement their own Error structure, so they would have to use `Either` anyway.

**Comment by spebbe** [comment]
Hi @iangregsondev!

I've only briefly scanned the links you sent, but I get the impression that the main difference is naming, not whether the "error"  type is fixed or not. Am I correct in that it is mainly different naming (`Right(...)` -> `Ok(...)`, `Left(...)` -> `Err(...)`) you are after, or am I misunderstanding something? Could you maybe provide an example of how you would like your code to look and work?

Thanks!

**Comment by mateusfccp** [comment]
> Hi @iangregsondev!
> 
> I've only briefly scanned the links you sent, but I get the impression that the main difference is naming, not whether the "error" type is fixed or not. Am I correct in that it is mainly different naming (`Right(...)` -> `Ok(...)`, `Left(...)` -> `Err(...)`) you are after, or am I misunderstanding something? Could you maybe provide an example of how you would like your code to look and work?
> 
> Thanks!

@spebbe, `Result` is virtually the same as `Either`, but with other names. Usually, it has the error side fixed in a specific type This is way I said Rust uses type aliases to deal with results.

For example, if you are using IO on Rust, you use IO lib [`Result`](https://doc.rust-lang.org/std/io/type.Result.html), which is a `Result` for IO errors. De definition of `Result` in this case, is `type Result<T> = Result<T, Error>;` which is virtually the same as `type Result<T> = Either<T, Error>;`

This is why I said that it doesn't make sense to make an `Result` type in-library, because `Result` types are fixed on specific errors, and not in a generic one.

**Comment by iangregsondev** [comment]
@spebbe Yes exactly its more or the less the same, but providing its own isOk, isErr - etc.

@mateusfccp sure, I understand all this. 

I have found this, https://pub.dev/packages/simple_result , which seems to do what I need.

Although I am going to attempt to use it similar to Either - sat with Option etc.

With regards to the EIther type, I have been watching the most excellent DDD (flutter) youtube series by resocoder.

It uses Union Types (from freezed) to populate the Either (left).

Seems to work really well.

Anyway, I will take a look at it further.

Thanks, everyone for the feedback.

**Comment by spebbe** [comment]
@iangregsondev, thanks for the suggestion!

Would some simple utils like this help you in any way?:
```dart
extension EitherAsResult<T, E> on Either<E, T> {
  bool isOk() => isRight();
  bool isErr() => isLeft();
}

Either<E, T> Ok<T, E>(T t) => right(t);
Either<E, T> Err<T, E>(E e) => left(e);
```

For a more convincing `Result` approximation, let's keep our fingers crossed that we get non-function type aliases soon!

**Comment by iangregsondev** [comment]
Thanks, @spebbe .

I think this would work in the meantime.
