### ISSUE TITLE
IMap<_,IList<_>> equals 

### ISSUE THREAD

**Issue by rich-j** [spebbe/dartz#6]
Should equivalent `IMap`s be equal?

    test('IMap with IList values equals', () {
      var m1 = new IMap.fromIterables([0,1], [new IList.from([2,4]), new IList.from([1,3,5])], new ComparableOrder<int>() );
      var m2 = new IMap.fromIterables([0,1], [new IList.from([2,4]), new IList.from([1,3,5])], new ComparableOrder<int>() );
      expect(m1, m1, reason: "same");
      expect(m1.keys(), m2.keys(), reason: "keys");
      expect(m1.get(0), m2.get(0), reason: "group 0");
      expect(m1.get(1), m2.get(1), reason: "group 1");
      expect(m1.values(), m2.values(), reason: "values");

      expect(m1, m2, reason: "equal");    // <-- fails
      expect(m1==m2, isTrue, reason: "also equal");   // <-- also fails
    });

Although the keys and values are equal, the `IMap`s are not.

I'm using the `ddc_compat` branch but running tests under the VM.

**Comment by spebbe** [comment]
Hi -- thanks for reporting!
Yep, I think they should! Defining equivalence is the problem here :-)

IMap '==' (universal) equality is defined by '==' equality of the sequence generated by in-order traversal of the key value pairs AND '==' equality of the contained Order instance. For example, two empty IMap<Int, String> instances are currently not considered equal if the first instance was instantiated with IntOrder and the other one with IntOrder.reverse(), since they will "behave differently" when identical sets of key value pairs are added to them (Euclid's second common notion: "If equals are added to equals, then the wholes are equal.").

Currently, ComparableOrder '==' equality is defined by reference equality... If you use a shared ComparableOrder<int> instance for both m1 and m2, your test will pass. There is also the constant 'IntOrder' available, that is a guaranteed singleton and slightly more efficient.

However, treating ComparableOrder<A> instances as equal for equal A sounds safe enough to me. I've pushed a change for this to the ddc_compat branch -- if you pull, your test should pass!

BTW, the line of reasoning above is just one, flawed attempt at defining equality in an imperfect world -- I'm completely open to other ways of attacking the problem if this way causes more problems than it solves.

**Comment by rich-j** [comment]
Of course...  I was so fixated on data equality that I missed the meta equality of `Order`. I was writing a quick test for a "simple" utility function and flummoxed by my test failing. Equality of `Order` is either a trivial identical check or a intractable comparison of implementation. Now that I have learned the lesson of `Order` equality I'm good with that meaning identical. The fix is probably a note that `Order` equality is based on identicalness and to consider implementing with a singleton.

I thought I had seen an `Order<int>` object but didn't find it in `order.dart`.  It's `IntOrder`, defined in `builtins.dart` and is capitalized suggesting a type...

Thanks

**Comment by rich-j** [comment]
Here's an excerpt of the code under test:

    /// Partition an IList into a set of groups with membership defined by a function result
    IMap<G, IList<A>> ilistGroupBy<A, G extends Comparable>(IList<A> l, G Function(A) f) =>
      l.foldLeft<IMap<G, IList<A>>>( emptyMap(), (acc, a) {
        var group = f(a);
        return acc.put( group, acc.get(group).fold( ()=>new IList.from([a]), (p)=>p.prependElement(a) ) );
      } ).map( (l)=>l.reverse() );      // Maintain original list order

and corresponding "offending" tests where I tried to create a "equivalent" structure for comparison:

    test('Group even/odd integers equals', () {
      var list = new IList.from([1,2,3,4,5]);
      var expected = new IMap.fromIterables([0,1], [new IList.from([2,4]), new IList.from([1,3,5])], comparableOrder() );
      var grouped = ilistGroupBy<int, int>(list, (n)=>n%2);     // Group by mod 2 remainder
      expect(grouped, expected, reason: "Expect equal ints");
    });

    test('Group strings by first letter', () {
      var list = new IList.from(["test", "not", "new", "try", "none"]);
      var expected = new IMap.fromIterables(["n","t"], [new IList.from(["not", "new", "none"]), new IList.from(["test", "try"])], comparableOrder() );
      var grouped = ilistGroupBy<String, String>(list, (s)=>s.substring(0,1));     // Extract first character
      expect(grouped, expected, reason: "Expect equal strings");
    });

These tests now work - Thanks!  I found that I needed to use `comparableOrder()` on the expected outcome creation.

Any suggestions for improvements?
