### ISSUE TITLE
How to use dartz filter function?

### ISSUE THREAD

**Issue by mwenechac** [spebbe/dartz#68]
I have this implementation, and I want to have access to the right side and then filter the list. I have added another map function as shown below but I cannot seem to make it work:

  yield* _firestore
        .collection('trips')
        .where('bus_stops.$destinationTown', isEqualTo: true)
        .where('bus_stops.$departureTown', isEqualTo: true)
        // .where('available_seats', isGreaterThanOrEqualTo: passengerCount)
        .where('trip_date', isEqualTo: travelDate)
        .snapshots()
        .map(
          (snapshot) => right<TripFailure, KtList<Trip>>(
            snapshot.docs
                .map((e) => TripDTO.fromFirestore(e).toDomain())
                .toImmutableList(),
          ).map((r) => r.filter(() => false))
        )

**Comment by spebbe** [comment]
Hi!

I can't really decipher your code without any context, but I'm going to assume you are referring to the `filter` method on `Either`. Is that correct? 

`Either#filter` applies a `predicate` function to `Right` values, leaving them unchanged if the `predicate` function evaluates to `true` and returning a `Left` of whatever the `fallback` function evaluates to otherwise. `Left` values are simply passed through.

Here are some examples:
```dart
  final a = right<String, int>(5);
  final b = left<String, int>("Out of integers");

  print(a.filter((i) => i%2==0, () => "only even integers allowed")); // prints: Left(only even integers allowed)
  print(a.filter((i) => i == 5, () => "five or nothing!"));           // prints: Right(5)

  print(b.filter((i) => i%2==0, () => "only even integers allowed")); // prints: Left(Out of integers)
  print(b.filter((i) => i == 5, () => "five or nothing!"));           // prints: Left(Out of integers)
```

**Comment by mwenechac** [comment]
Thank you @spebbe . 
That was very helpful.
